### ISSUE TITLE
[BUG] Remove redundant NAT gateway resource

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/m-aws-kubernetes-service#12]
After this refactor https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/17 awsks code contains unneeded NAT gateway resource (it generates extra costs!). We'd like to get rid of it! :+1::innocent:

**Comment by atsikham** [comment]
Should it be closed as #13 PR has been already merged?

**Comment by atsikham** [comment]
Will be tested together with [related](https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/17) issue.

**Comment by atsikham** [comment]
Verified that there is no NAT gateway and eip created in awsks module. This part was moved to awsbi.
