### ISSUE TITLE
 Add more parameter in order to create customizable, private EKS cluster

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/m-aws-kubernetes-service#17]
**Is your feature request related to a problem?** 
Right now, we can customize only a few parameters in our EKS module: 

```
M_NAME ?= epiphany
M_VPC_ID ?= unset
M_PUBLIC_SUBNET_ID ?= unset
M_REGION ?= eu-central-1
```

**Describe the solution you'd like**
We would like to create fully customizable private cluster, with all useful options which can be needed such as: 

- worker_groups [instance_type, asg_desired_capacity, asg_min_size, asg_max_size]
- autoscaler_scale_down_utilization_threshold
- instance_attributes [disk_size]
- vms_rsa

From similar task for [AKS module](https://github.com/epiphany-platform/m-azure-kubernetes-service/issues/8):
- public_ip_enabled
- network_plugin
- network_policy
- auto_scaler_profile 
- rbac_enabled
- node_type

**Describe alternatives you've considered**
n/a

**Additional context**
Here we have AKS example how the fully customizable private cluster should look like: [link](https://github.com/epiphany-platform/build-system/tree/develop/technical/sources/terraform/modules/aks)

**Comment by atsikham** [comment]
Description seems to be ok, but before doing this I suggest to do #6, as it can affect parameters.

**Comment by atsikham** [comment]
In the same task for AKS we decided that network plugin and network policy are not allowed to be set bu user.

**Comment by toszo** [comment]
Waiting for #6 to finish.

**Comment by atsikham** [comment]
This task is unblocked.

**Comment by przemyslavic** [comment]
@ar3ndt please connect this task with PR.

**Comment by przemyslavic** [comment]
@ar3ndt please fix the following:
1. The `asg_min_size` parameter is confused with the `asg_max_size` parameter. They work the opposite of what they should.
```
  scaling_config {
    desired_size = var.worker_groups[count.index].asg_desired_capacity
    max_size     = var.worker_groups[count.index].asg_min_size
    min_size     = var.worker_groups[count.index].asg_max_size
  }
```
2. Please update the `INPUTS.adoc` document with the newly added parameters.

**Comment by przemyslavic** [comment]
Fixed.
