### ISSUE TITLE
 Allow to create EKS in already existing subnet

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/m-aws-kubernetes-service#18]
Same as for [AKS module](https://github.com/epiphany-platform/m-azure-kubernetes-service/issues/7).
This is to use the existing VPC for the EKS cluster.
We need the possibility to specify VPC and subnets in the create cluster command to reuse the preconfigured VPC and subnets.

**Comment by rpudlowski93** [comment]
Ability to run EKS in existing subnets added in PR #21.

**Comment by ar3ndt** [comment]
Test OK. EKS created with provided subnets

**Comment by atsikham** [comment]
Just figured it out - please consider to implement tagging for subnets - https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-subnet-tagging. I can implement that in the scope of #6, but in this case we must test it there.

**Comment by atsikham** [comment]
Waiting for @rpudlowski93, so moved to `on hold`.

**Comment by rpudlowski93** [comment]
In this module we give ability to: 
- create subnets and deploy eks there. In this case we already have implemented subnet tagging : `./resources/terraform/main.tf`
- create eks in already existing subnets, it means that we don't care of subnets and vpc, just deploy EKS in the ready to use subnets and in documentation it is already mentioned that: 

> The existing VPC must meet specific [requirements](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html) for use with Amazon EKS

In the requirements link there is mentioned the tagging requirement. In my opinion, nothing to add.

**Comment by atsikham** [comment]
> In the requirements link there is mentioned the tagging requirement. In my opinion, nothing to add.

In my opinion, there is. Let's imagine the flow when you create EC2/VPC resources in AWSBI module and don't tag them as you don't know at that moment how this infrastructure will be used. So when you deploy EKS on top of these infrastructure, you should care about following requirements and subnet tagging.

**Comment by rpudlowski93** [comment]
Ok, I wasn't conscious of the task #[6](https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/6). So, If we want to move the subnet creation process from AwsKS into AwsBI, I can agree that we should add tagging passed subnets in AwsKS. I already created a new task #[25](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/25) for that which is depend on the task #6. Right now, we create new subnets and tag them in AwsKS. We should start testing the task and close it and start working on the mentioned improvements.

**Comment by atsikham** [comment]
@rpudlowski93 I think that if nothing was changed, you can move it further as it has been already tested by @ar3ndt

**Comment by rpudlowski93** [comment]
True :)
