### ISSUE TITLE
[FEATURE REQUEST] Pass name and region parameters in pipeline

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/m-aws-kubernetes-service#41]
**Is your feature request related to a problem? Please describe.**
At the moment when `integration_test.go` is executed (or `make test`), resources are created with default names and in default region. We need to have an ability to change resource name prefixes during test execution to identify them  and also specify diffirent regions, because sometimes there are problems with resources creation as limit per region exceeded.

**Describe the solution you'd like**
1. Add an ability to pass M_NAME and M_REGION parameters for tests execution, do that for calling both - awsbi and awsks images (there is awsbi image used as before creation of k8s cluster infrastructure is created).
2. In pipeline pass M_NAME that is depended from pipeline id or any other unique value. It should be possible to identify by AWS resource name what it is used for.
3. In pipeline pass M_REGION, so it can be easilly changed when necessary.

**Describe alternatives you've considered**
No.

**Additional context**
Check pipeline configuration and "test" target in Makefile.

**Comment by przemyslavic** [comment]
Added ability to set resource name prefix and region for tests. If environment variables are not set, default values are used. For a pipeline, the prefix includes `BuildId` so that we can easily identify the created resources.
