### ISSUE TITLE
[BUG] Key pairs are not properly removed after test execution

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/m-aws-kubernetes-service#42]
**Describe the bug**
Resources are not removed properly after tests execution

**How to reproduce**
1. Build AWSBI image: `make build`, it will build the image with the tag `docker.io/epiphanyplatform/awsbi:0.0.1`
2. AWSKS image will be built by `make test` later, no actions required for that
3. Set necessary variables:
```bash
export AWSKS_IMAGE_TAG=docker.io/epiphanyplatform/awsks:0.0.1
export AWSBI_IMAGE_TAG=docker.io/epiphanyplatform/awsbi:0.0.1
```
4. Run `make test`: 
Key-pair is not removed, as it's created with random string in name and removed by tests incorrectly, we should remove it by tags (this behaviour can be reproduced by running a pipeline).

**Expected behavior**
All resources created by tests are removed after execution.

**Config files**
There is no any required config files.

**Additional context**
The part of this issue is not reproduced by pipeline, check manually with latest module versions.

**Comment by atsikham** [comment]
This issue will be taken after #44 is merged not to mix related changes.

**Comment by atsikham** [comment]
PRs are created for both AWS modules.

**Comment by przemyslavic** [comment]
Modules `m-aws-basic-infrastructure` and `m-aws-kubernetes-service` were tested.
The tests were run locally with `make test` command and in the pipelines.
Key pairs are now tagged and removed correctly in tests.
