### ISSUE TITLE
Document Component and dependency versions and licenses

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-aws-kubernetes-service#5]
Like [this](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/COMPONENTS.md) but preferred is automatic generation.

**Comment by atsikham** [comment]
Readme "Dependencies" section can be useful for this task.

**Comment by mkyc** [comment]
Yeah, you meant of PR #4

**Comment by atsikham** [comment]
@mkyc But if we need automatic generation, it isn't so. Maybe it's possible to create a tool to do this for all modules: check terraform dependencies, check Dockerfile and generate licenses doc.

**Comment by mkyc** [comment]
I added `preferred is automatic generation` in description and now it's probably not a good moment to implement it. I'll create separate task for automation of this element.
