### ISSUE TITLE
Replace terraform-aws-eks module by eks_cluster resource

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/m-aws-kubernetes-service#6]
There is an embedded [ability](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster) to create EKS cluster by terraform.
But as a result of [spike](https://github.com/epiphany-platform/epiphany/issues/1442) we use [aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) module that has issues that are described in [this ](https://github.com/epiphany-platform/m-aws-kubernetes-service/pull/4) PR.

Suggestion is to replace these things with ability to install EKS with k8s v1.18 and v1.19. That will help us to achieve easier support for functionality that we want.

Expectations:
1. Terraform eks_cluster [resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster) usage.
2. Ability to install EKS with k8s v1.18 and 1.19.
3. Changed dependencies versions info, at the moment of task creation that's located in readme.
4. Changed default k8s version.
5. Probably no need of 'make -k' option usage to destroy resources, so readme is updated.

**Comment by przemyslavic** [comment]
I found an issue executing the `plan` command:

```make: [Makefile:175: module-plan] Error 1 (ignored)
#AWSKS | terraform-plan | will run plan
Error: Cycle: module.control_plane.output.cluster_name (expand), aws_subnet.eks_subnet, local.subnet_ids (expand), module.control_plane.var.subnet_ids (expand), module.control_plane.aws_iam_role_policy_attachment.eks_iam_cluster_policy_attachment, module.control_plane.aws_iam_role.eks_cluster_iam_role, module.control_plane.aws_iam_role_policy_attachment.eks_iam_vpc_resource_controller_attachment, module.control_plane.aws_eks_cluster.eks_cluster
make: *** [Makefile:36: terraform-plan] Error 1
```

**Comment by przemyslavic** [comment]
✅ I have successfully deployed an EKS cluster using awsbi and awsks modules.
